### ISSUE TITLE
cannot reproduce code

### ISSUE THREAD

**Issue by linjikun1** [CupCupRay/Bin2Summary#2]
Hi, 

Since my CUDA version is too high, so the conda env is **python==3.8, tensorflow-gpu==2.9.0, cudatoolkit==11.2, cudnn==8.1**.

When generating function embedding with **PalnTree**, **Asm2vec** and **DeepBinDiff**, a similar error occured:
> ModuleNotFoundError: No module named 'binaryninja'

The error points to [line 6 in gen_asm.py](https://github.com/CupCupRay/Bin2Summary/blob/a6afb97903c12d674bc3c6073ec36f0a51e9461d/src/palmtree_emb/gen_asm.py#L6) and [line 9 in use_depgraph.py](https://github.com/CupCupRay/Bin2Summary/blob/a6afb97903c12d674bc3c6073ec36f0a51e9461d/src/utils/use_depgraph.py#L9).

**My problems are as follows:**
1. Is there a problem with my conda environment?
2. I try to install binaryninja module according to [this link](https://github.com/Vector35/binaryninja-api/blob/dev/scripts/install_api.py). But I found that I needed to buy the commercial version of BinaryNinja to have access to the API, which seem to be essential to install binaryninja module. So how do I `import binaryninja`?
3. Will the version required [here](https://github.com/CupCupRay/Bin2Summary/blob/a6afb97903c12d674bc3c6073ec36f0a51e9461d/src/deepbindiff_emb/README.md?plain=1#L7) conflict with the [previous one](https://github.com/CupCupRay/Bin2Summary/blob/a6afb97903c12d674bc3c6073ec36f0a51e9461d/README.md?plain=1#L25)?

**Comment by CupCupRay** [comment]
Hi, @ljk419511,

Thank you for your interest!

From your error message, I think this is the problem with BinaryNinja. In my experiments, I used the commercial version of BinaryNinja (since only the commercial version can provide API without UI). For the other version of dependencies, I haven't tried to use a higher CUDA version in my environment, so I am not sure if there will be any problems during the experiments. But currently, I think this is due to the lack of BinaryNinja, and a commercial version of BinaryNinja is necessary.

Hope this will answer your question.

Best regards,
Ray
